# Generated by Django 2.2 on 2019-07-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_mysqlinitinfo_hostname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqlinitinfo',
            name='hostname',
        ),
    ]
